export const ADHKAR_CATEGORIES = [
  { id: 'sabah',    label: 'Morning', labelAr: 'أذكار الصباح',     emoji: '🌅', color: '#c9952a' },
  { id: 'masa',     label: 'Evening', labelAr: 'أذكار المساء',     emoji: '🌙', color: '#5b3a8a' },
  { id: 'salah',    label: 'After Prayer', labelAr: 'أذكار بعد الصلاة', emoji: '🤲', color: '#2d9b6f' },
  { id: 'nawm',     label: 'Sleep',   labelAr: 'أذكار النوم',      emoji: '✨', color: '#1a4a6b' },
  { id: 'himaya',   label: 'Protection', labelAr: 'أذكار الحماية', emoji: '🛡️', color: '#6b1a1a' },
  { id: 'ruqyah',   label: 'Ruqyah',  labelAr: 'الرقية الشرعية',  emoji: '⚡', color: '#4a3a1a' },
]

export const ADHKAR = {
  sabah: [
    {
      id: 's1', count: 1,
      arabic: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\n﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾',
      translation: 'Ayat Al-Kursi — The Throne Verse',
      translationAr: 'آية الكرسي',
      source: 'سورة البقرة 255',
      benefit: 'من قرأها في الصباح حُفظ من الشيطان حتى المساء',
    },
    {
      id: 's2', count: 3,
      arabic: '﴿قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ﴾',
      translation: 'Surah Al-Ikhlas (x3)',
      translationAr: 'سورة الإخلاص',
      source: 'سورة الإخلاص',
      benefit: 'تعدل ثلث القرآن',
    },
    {
      id: 's3', count: 3,
      arabic: '﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ مِن شَرِّ مَا خَلَقَ ۝ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ۝ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ﴾',
      translation: 'Surah Al-Falaq (x3) — Protection from all evil',
      translationAr: 'سورة الفلق — الحماية من شر المخلوقات',
      source: 'سورة الفلق',
      benefit: 'حماية من السحر والحسد وشر الخلق',
    },
    {
      id: 's4', count: 3,
      arabic: '﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَٰهِ النَّاسِ ۝ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الْجِنَّةِ وَالنَّاسِ﴾',
      translation: 'Surah Al-Nas (x3) — Protection from whispers',
      translationAr: 'سورة الناس — الحماية من وسواس الشيطان',
      source: 'سورة الناس',
      benefit: 'حماية من وسواس الجن والإنس',
    },
    {
      id: 's5', count: 1,
      arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَـهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ',
      translation: 'We have reached the morning and the whole kingdom belongs to Allah...',
      translationAr: 'دعاء الصباح',
      source: 'مسلم',
      benefit: 'استفتاح اليوم بذكر الله وطلب خير اليوم',
    },
    {
      id: 's6', count: 1,
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ',
      translation: 'O Allah, You are my Lord, there is no god but You. You created me and I am Your servant...',
      translationAr: 'سيد الاستغفار',
      source: 'البخاري',
      benefit: 'سيد الاستغفار — من قاله موقناً فمات من يومه دخل الجنة',
    },
    {
      id: 's7', count: 10,
      arabic: 'لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      translation: 'There is no god but Allah, alone, without partner. His is the dominion and His is the praise and He is over all things omnipotent.',
      translationAr: 'التهليل',
      source: 'مسلم',
      benefit: 'كانت له عدل عشر رقاب وكُتب له مائة حسنة ومُحيت عنه مائة سيئة',
    },
    {
      id: 's8', count: 3,
      arabic: 'رَضِيتُ بِاللهِ رَبًّا، وَبِالإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صلى الله عليه وسلم نَبِيًّا',
      translation: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad ﷺ as my Prophet.',
      translationAr: 'الرضا بالله رباً',
      source: 'أبو داود والترمذي',
      benefit: 'حق على الله أن يرضيه يوم القيامة',
    },
    {
      id: 's9', count: 1,
      arabic: 'اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لاَ إِلَهَ إِلاَّ أَنْتَ',
      translation: 'O Allah, grant me health in my body, health in my hearing, health in my sight. There is none worthy of worship except You.',
      translationAr: 'طلب العافية',
      source: 'أبو داود',
      benefit: 'طلب العافية في الجسد والحواس',
    },
    {
      id: 's10', count: 7,
      arabic: 'حَسْبِيَ اللهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      translation: 'Allah is sufficient for me; there is no deity but Him. I have placed my trust in Him and He is the Lord of the Magnificent Throne.',
      translationAr: 'حسبي الله',
      source: 'أبو داود',
      benefit: 'من قالها سبع مرات كفاه الله ما أهمه',
    },
    {
      id: 's11', count: 3,
      arabic: 'بِسْمِ اللهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      translation: 'In the name of Allah, Who with His name nothing can cause harm in the earth nor in the heavens, and He is the All-Hearing, the All-Knowing.',
      translationAr: 'التحصين باسم الله',
      source: 'أبو داود والترمذي',
      benefit: 'لم يضره شيء',
    },
    {
      id: 's12', count: 3,
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      translationAr: 'التعوذ بكلمات الله',
      source: 'مسلم',
      benefit: 'لم تضره حُمة تلك الليلة',
    },
    {
      id: 's13', count: 100,
      arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
      translation: 'Glory be to Allah and praise Him.',
      translationAr: 'التسبيح والتحميد',
      source: 'البخاري ومسلم',
      benefit: 'من قالها مئة مرة حُطّت خطاياه وإن كانت مثل زبد البحر',
    },
    {
      id: 's14', count: 10,
      arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
      translation: 'O Allah, send prayers and peace and blessings upon our Prophet Muhammad.',
      translationAr: 'الصلاة على النبي ﷺ',
      source: 'السنة النبوية',
      benefit: 'كُفي همه وغفر ذنبه',
    },
  ],

  masa: [
    {
      id: 'm1', count: 1,
      arabic: 'أَعُوذُ بِاللهِ مِنَ الشَّيْطَانِ الرَّجِيمِ\n﴿اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ...﴾',
      translation: 'Ayat Al-Kursi',
      translationAr: 'آية الكرسي',
      source: 'سورة البقرة 255',
      benefit: 'من قرأها في المساء حُفظ من الشيطان حتى الصباح',
    },
    {
      id: 'm2', count: 3,
      arabic: '﴿قُلْ هُوَ اللَّهُ أَحَدٌ﴾ — ﴿قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ﴾ — ﴿قُلْ أَعُوذُ بِرَبِّ النَّاسِ﴾',
      translation: 'Al-Ikhlas, Al-Falaq, Al-Nas (x3 each)',
      translationAr: 'المعوذات الثلاث',
      source: 'أبو داود والترمذي',
      benefit: 'تكفيك من كل شيء',
    },
    {
      id: 'm3', count: 1,
      arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَـهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا',
      translation: 'We have entered the evening and at this very time the whole dominion belongs to Allah...',
      translationAr: 'دعاء المساء',
      source: 'مسلم',
      benefit: 'استفتاح المساء بذكر الله',
    },
    {
      id: 'm4', count: 1,
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ',
      translation: 'Sayyid Al-Istighfar — Master supplication for forgiveness',
      translationAr: 'سيد الاستغفار',
      source: 'البخاري',
      benefit: 'من قاله موقناً فمات من ليلته دخل الجنة',
    },
    {
      id: 'm5', count: 7,
      arabic: 'حَسْبِيَ اللهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      translation: 'Allah is sufficient for me; there is no deity but Him.',
      translationAr: 'حسبي الله',
      source: 'أبو داود',
      benefit: 'كفاه الله ما أهمه في دنياه وآخرته',
    },
    {
      id: 'm6', count: 3,
      arabic: 'بِسْمِ اللهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
      translation: 'In the name of Allah, with Whose name nothing can cause harm.',
      translationAr: 'التحصين باسم الله',
      source: 'أبو داود',
      benefit: 'لم يضره شيء',
    },
    {
      id: 'm7', count: 3,
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      translation: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
      translationAr: 'التعوذ من شر الخلق',
      source: 'مسلم',
      benefit: 'لم تضره حُمة تلك الليلة',
    },
    {
      id: 'm8', count: 10,
      arabic: 'اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى نَبِيِّنَا مُحَمَّدٍ',
      translation: 'O Allah, send prayers, peace and blessings upon our Prophet Muhammad.',
      translationAr: 'الصلاة على النبي ﷺ',
      source: 'السنة النبوية',
      benefit: 'كُفي همه وغفر ذنبه',
    },
    {
      id: 'm9', count: 100,
      arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
      translation: 'Glory be to Allah and praise Him.',
      translationAr: 'التسبيح',
      source: 'البخاري ومسلم',
      benefit: 'حُطّت خطاياه وإن كانت مثل زبد البحر',
    },
  ],

  salah: [
    {
      id: 'p1', count: 3,
      arabic: 'أَسْتَغْفِرُ اللهَ',
      translation: 'I seek forgiveness of Allah.',
      translationAr: 'الاستغفار',
      source: 'مسلم',
      benefit: 'ثلاثاً بعد كل صلاة',
    },
    {
      id: 'p2', count: 1,
      arabic: 'اللَّهُمَّ أَنْتَ السَّلاَمُ، وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ ذَا الْجَلاَلِ وَالإِكْرَامِ',
      translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, O Possessor of majesty and honor.',
      translationAr: 'دعاء انصراف الصلاة',
      source: 'مسلم',
      benefit: 'يقال بعد السلام من الصلاة',
    },
    {
      id: 'p3', count: 33,
      arabic: 'سُبْحَانَ اللهِ',
      translation: 'Glory be to Allah.',
      translationAr: 'التسبيح',
      source: 'مسلم',
      benefit: '٣٣ مرة بعد كل صلاة',
    },
    {
      id: 'p4', count: 33,
      arabic: 'الْحَمْدُ للهِ',
      translation: 'All praise is for Allah.',
      translationAr: 'التحميد',
      source: 'مسلم',
      benefit: '٣٣ مرة بعد كل صلاة',
    },
    {
      id: 'p5', count: 33,
      arabic: 'اللهُ أَكْبَرُ',
      translation: 'Allah is the Greatest.',
      translationAr: 'التكبير',
      source: 'مسلم',
      benefit: '٣٣ مرة بعد كل صلاة',
    },
    {
      id: 'p6', count: 1,
      arabic: 'لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      translation: 'There is no deity but Allah, alone without partners. To Him belongs the dominion and to Him belongs the praise, and He is over all things omnipotent.',
      translationAr: 'ختم التسبيح',
      source: 'مسلم',
      benefit: 'تُغفر ذنوبه وإن كانت مثل زبد البحر',
    },
  ],

  nawm: [
    {
      id: 'n1', count: 1,
      arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      translation: 'In Your name, O Allah, I die and I live.',
      translationAr: 'ذكر النوم',
      source: 'البخاري',
      benefit: 'يُقال عند النوم',
    },
    {
      id: 'n2', count: 1,
      arabic: 'اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ',
      translation: 'O Allah, protect me from Your punishment on the Day You resurrect Your servants.',
      translationAr: 'دعاء النوم',
      source: 'أبو داود',
      benefit: 'يُقال ثلاث مرات عند النوم',
    },
    {
      id: 'n3', count: 33,
      arabic: 'سُبْحَانَ اللهِ — ٣٣\nالْحَمْدُ للهِ — ٣٣\nاللهُ أَكْبَرُ — ٣٤',
      translation: 'Tasbih of Fatimah: SubhanAllah x33, Alhamdulillah x33, Allahu Akbar x34',
      translationAr: 'تسبيح فاطمة رضي الله عنها',
      source: 'البخاري ومسلم',
      benefit: 'خير لكما مما سألتما',
    },
    {
      id: 'n4', count: 1,
      arabic: '﴿الَّذِي بِيَدِهِ الْمُلْكُ...﴾ سورة الملك كاملة',
      translation: 'Surah Al-Mulk (full) — protects from the punishment of the grave',
      translationAr: 'سورة الملك',
      source: 'الترمذي',
      benefit: 'المانعة من عذاب القبر',
    },
    {
      id: 'n5', count: 1,
      arabic: '﴿آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ...﴾ آخر سورة البقرة',
      translation: 'Last two verses of Al-Baqarah',
      translationAr: 'خواتيم سورة البقرة',
      source: 'البخاري',
      benefit: 'كفتاه — من قرأهما في ليلة كفتاه',
    },
  ],

  himaya: [
    {
      id: 'h1', count: 3,
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لاَمَّةٍ',
      translation: 'I seek refuge in the complete words of Allah from every devil and every poisonous thing, and from every harmful evil eye.',
      translationAr: 'الحماية من العين والشيطان',
      source: 'البخاري',
      benefit: 'كان النبي ﷺ يعوّذ بها الحسن والحسين — حماية من العين والجن',
    },
    {
      id: 'h2', count: 1,
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
      translation: 'O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from cowardice and miserliness, from being overcome by debt and overpowered by men.',
      translationAr: 'الحماية الشاملة',
      source: 'البخاري',
      benefit: 'الحماية الشاملة من آفات النفس والدنيا',
    },
    {
      id: 'h3', count: 7,
      arabic: 'حَسْبِيَ اللهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      translation: 'Allah is sufficient for me. There is no deity but Him, in Him I put my trust, and He is the Lord of the Magnificent Throne.',
      translationAr: 'حسبي الله — التوكل',
      source: 'أبو داود',
      benefit: 'كفاه الله ما أهمه',
    },
    {
      id: 'h4', count: 1,
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْفَقْرِ وَالْقِلَّةِ وَالذِّلَّةِ، وَأَعُوذُ بِكَ مِنْ أَنْ أَظْلِمَ أَوْ أُظْلَمَ',
      translation: 'O Allah, I seek refuge in You from poverty, scarcity and humiliation, and I seek refuge in You from wronging or being wronged.',
      translationAr: 'الحماية من الفقر والظلم',
      source: 'النسائي وأبو داود',
      benefit: 'حماية من الفقر والظلم والذل',
    },
    {
      id: 'h5', count: 1,
      arabic: 'اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ، وَمِنْ خَلْفِي، وَعَنْ يَمِينِي، وَعَنْ شِمَالِي، وَمِنْ فَوْقِي، وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي',
      translation: 'O Allah, protect me from my front, from behind me, from my right, from my left, from above me, and I seek refuge in Your greatness from being swallowed up from below.',
      translationAr: 'الحفظ الشامل من كل اتجاه',
      source: 'أبو داود',
      benefit: 'حفظ من جميع الجهات',
    },
    {
      id: 'h6', count: 3,
      arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ',
      translation: 'O Allah, with You we begin the morning, with You we begin the evening, with You we live and with You we die, and to You is the return.',
      translationAr: 'التعلق بالله في كل حال',
      source: 'الترمذي',
      benefit: 'ربط الحياة كلها بالله',
    },
  ],

  ruqyah: [
    {
      id: 'r1', count: 1,
      arabic: 'بِسْمِ اللهِ أَرْقِيكَ، مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنٍ حَاسِدٍ، اللهُ يَشْفِيكَ، بِسْمِ اللهِ أَرْقِيكَ',
      translation: 'In the name of Allah I perform Ruqyah on you, from everything that harms you, from the evil of every soul or envious eye. May Allah heal you.',
      translationAr: 'رقية جبريل — للآخرين',
      source: 'مسلم',
      benefit: 'رقية النبي ﷺ بها جبريل',
    },
    {
      id: 'r2', count: 3,
      arabic: 'أَعُوذُ بِاللهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ',
      translation: 'I seek refuge in Allah and His power from the evil of what I feel and what I guard against.',
      translationAr: 'رقية الألم — توضع اليد على الموضع المؤلم',
      source: 'مسلم',
      benefit: 'يضع يده على الموضع المؤلم ويقولها سبعاً',
    },
    {
      id: 'r3', count: 1,
      arabic: '﴿وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ﴾\n\nسورة الفاتحة × ٧\nآية الكرسي × ١\nسورة الإخلاص × ٣\nسورة الفلق × ٣\nسورة الناس × ٣',
      translation: 'Full Ruqyah protocol: Al-Fatiha x7, Ayat Al-Kursi x1, Al-Ikhlas x3, Al-Falaq x3, Al-Nas x3',
      translationAr: 'الرقية الشرعية الكاملة',
      source: 'السنة النبوية',
      benefit: 'الرقية الكاملة للعين والسحر والحسد والجن',
    },
    {
      id: 'r4', count: 1,
      arabic: 'اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِهِ وَأَنْتَ الشَّافِي، لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ، شِفَاءً لاَ يُغَادِرُ سَقَمَاً',
      translation: 'O Allah, Lord of mankind, remove the harm and heal. You are the Healer. There is no healing except Your healing — a healing that leaves no ailment.',
      translationAr: 'دعاء الشفاء',
      source: 'البخاري ومسلم',
      benefit: 'دعاء النبي ﷺ للمريض',
    },
    {
      id: 'r5', count: 7,
      arabic: '﴿الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ۝ الرَّحْمَٰنِ الرَّحِيمِ ۝ مَالِكِ يَوْمِ الدِّينِ ۝ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ﴾',
      translation: 'Surah Al-Fatiha x7 — The greatest Ruqyah',
      translationAr: 'سورة الفاتحة × ٧ — أم الرقية',
      source: 'البخاري',
      benefit: 'كلُّ داء ولا يُستثنى منها شيء',
    },
  ],
}

export const DAILY_VERSES = [
  { arabic: 'وَمَن يَتَّقِ اللَّهَ يَجْعَل لَّهُ مَخْرَجًا', ref: 'الطلاق 2', en: 'Whoever fears Allah — He will make for him a way out.' },
  { arabic: 'إِنَّ مَعَ الْعُسْرِ يُسْرًا', ref: 'الشرح 6', en: 'Indeed, with hardship comes ease.' },
  { arabic: 'وَفِي السَّمَاءِ رِزْقُكُمْ وَمَا تُوعَدُونَ', ref: 'الذاريات 22', en: 'And in the heaven is your provision and what you are promised.' },
  { arabic: 'فَاصْبِرْ إِنَّ اللَّهَ مَعَ الصَّابِرِينَ', ref: 'الأنفال 46', en: 'Be patient; indeed Allah is with the patient.' },
  { arabic: 'وَمَا تَوْفِيقِي إِلَّا بِاللَّهِ', ref: 'هود 88', en: 'My success is not but through Allah.' },
  { arabic: 'إِنَّ اللَّهَ لَا يُضِيعُ أَجْرَ الْمُحْسِنِينَ', ref: 'هود 115', en: 'Allah does not allow the reward of the doers of good to be lost.' },
  { arabic: 'وَاللَّهُ غَالِبٌ عَلَىٰ أَمْرِهِ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ', ref: 'يوسف 21', en: 'And Allah is predominant over His affair, but most people do not know.' },
]
