// All 114 Surahs
export const SURAHS = [
  { n:1,   ar:'الفاتحة',       en:'Al-Fatiha',        ayahs:7,   type:'Meccan',  juz:1  },
  { n:2,   ar:'البقرة',        en:'Al-Baqarah',       ayahs:286, type:'Medinan', juz:1  },
  { n:3,   ar:'آل عمران',      en:"Ali 'Imran",       ayahs:200, type:'Medinan', juz:3  },
  { n:4,   ar:'النساء',        en:'An-Nisa',          ayahs:176, type:'Medinan', juz:4  },
  { n:5,   ar:'المائدة',       en:"Al-Ma'idah",       ayahs:120, type:'Medinan', juz:6  },
  { n:6,   ar:'الأنعام',       en:"Al-An'am",         ayahs:165, type:'Meccan',  juz:7  },
  { n:7,   ar:'الأعراف',       en:"Al-A'raf",         ayahs:206, type:'Meccan',  juz:8  },
  { n:8,   ar:'الأنفال',       en:'Al-Anfal',         ayahs:75,  type:'Medinan', juz:9  },
  { n:9,   ar:'التوبة',        en:'At-Tawbah',        ayahs:129, type:'Medinan', juz:10 },
  { n:10,  ar:'يونس',          en:'Yunus',            ayahs:109, type:'Meccan',  juz:11 },
  { n:11,  ar:'هود',           en:'Hud',              ayahs:123, type:'Meccan',  juz:11 },
  { n:12,  ar:'يوسف',          en:'Yusuf',            ayahs:111, type:'Meccan',  juz:12 },
  { n:13,  ar:'الرعد',         en:"Ar-Ra'd",          ayahs:43,  type:'Medinan', juz:13 },
  { n:14,  ar:'إبراهيم',       en:'Ibrahim',          ayahs:52,  type:'Meccan',  juz:13 },
  { n:15,  ar:'الحجر',         en:'Al-Hijr',          ayahs:99,  type:'Meccan',  juz:14 },
  { n:16,  ar:'النحل',         en:'An-Nahl',          ayahs:128, type:'Meccan',  juz:14 },
  { n:17,  ar:'الإسراء',       en:"Al-Isra'",         ayahs:111, type:'Meccan',  juz:15 },
  { n:18,  ar:'الكهف',         en:'Al-Kahf',          ayahs:110, type:'Meccan',  juz:15 },
  { n:19,  ar:'مريم',          en:'Maryam',           ayahs:98,  type:'Meccan',  juz:16 },
  { n:20,  ar:'طه',            en:'Ta-Ha',            ayahs:135, type:'Meccan',  juz:16 },
  { n:21,  ar:'الأنبياء',      en:'Al-Anbiya',        ayahs:112, type:'Meccan',  juz:17 },
  { n:22,  ar:'الحج',          en:'Al-Hajj',          ayahs:78,  type:'Medinan', juz:17 },
  { n:23,  ar:'المؤمنون',      en:"Al-Mu'minun",      ayahs:118, type:'Meccan',  juz:18 },
  { n:24,  ar:'النور',         en:'An-Nur',           ayahs:64,  type:'Medinan', juz:18 },
  { n:25,  ar:'الفرقان',       en:'Al-Furqan',        ayahs:77,  type:'Meccan',  juz:18 },
  { n:26,  ar:'الشعراء',       en:"Ash-Shu'ara",      ayahs:227, type:'Meccan',  juz:19 },
  { n:27,  ar:'النمل',         en:'An-Naml',          ayahs:93,  type:'Meccan',  juz:19 },
  { n:28,  ar:'القصص',         en:'Al-Qasas',         ayahs:88,  type:'Meccan',  juz:20 },
  { n:29,  ar:'العنكبوت',      en:"Al-'Ankabut",      ayahs:69,  type:'Meccan',  juz:20 },
  { n:30,  ar:'الروم',         en:'Ar-Rum',           ayahs:60,  type:'Meccan',  juz:21 },
  { n:31,  ar:'لقمان',         en:'Luqman',           ayahs:34,  type:'Meccan',  juz:21 },
  { n:32,  ar:'السجدة',        en:'As-Sajdah',        ayahs:30,  type:'Meccan',  juz:21 },
  { n:33,  ar:'الأحزاب',       en:'Al-Ahzab',         ayahs:73,  type:'Medinan', juz:21 },
  { n:34,  ar:'سبأ',           en:'Saba',             ayahs:54,  type:'Meccan',  juz:22 },
  { n:35,  ar:'فاطر',          en:'Fatir',            ayahs:45,  type:'Meccan',  juz:22 },
  { n:36,  ar:'يس',            en:'Ya-Sin',           ayahs:83,  type:'Meccan',  juz:22 },
  { n:37,  ar:'الصافات',       en:'As-Saffat',        ayahs:182, type:'Meccan',  juz:23 },
  { n:38,  ar:'ص',             en:'Sad',              ayahs:88,  type:'Meccan',  juz:23 },
  { n:39,  ar:'الزمر',         en:'Az-Zumar',         ayahs:75,  type:'Meccan',  juz:23 },
  { n:40,  ar:'غافر',          en:'Ghafir',           ayahs:85,  type:'Meccan',  juz:24 },
  { n:41,  ar:'فصلت',          en:'Fussilat',         ayahs:54,  type:'Meccan',  juz:24 },
  { n:42,  ar:'الشورى',        en:'Ash-Shura',        ayahs:53,  type:'Meccan',  juz:25 },
  { n:43,  ar:'الزخرف',        en:'Az-Zukhruf',       ayahs:89,  type:'Meccan',  juz:25 },
  { n:44,  ar:'الدخان',        en:'Ad-Dukhan',        ayahs:59,  type:'Meccan',  juz:25 },
  { n:45,  ar:'الجاثية',       en:'Al-Jathiyah',      ayahs:37,  type:'Meccan',  juz:25 },
  { n:46,  ar:'الأحقاف',       en:'Al-Ahqaf',         ayahs:35,  type:'Meccan',  juz:26 },
  { n:47,  ar:'محمد',          en:'Muhammad',         ayahs:38,  type:'Medinan', juz:26 },
  { n:48,  ar:'الفتح',         en:'Al-Fath',          ayahs:29,  type:'Medinan', juz:26 },
  { n:49,  ar:'الحجرات',       en:'Al-Hujurat',       ayahs:18,  type:'Medinan', juz:26 },
  { n:50,  ar:'ق',             en:'Qaf',              ayahs:45,  type:'Meccan',  juz:26 },
  { n:51,  ar:'الذاريات',      en:'Adh-Dhariyat',     ayahs:60,  type:'Meccan',  juz:26 },
  { n:52,  ar:'الطور',         en:'At-Tur',           ayahs:49,  type:'Meccan',  juz:27 },
  { n:53,  ar:'النجم',         en:'An-Najm',          ayahs:62,  type:'Meccan',  juz:27 },
  { n:54,  ar:'القمر',         en:'Al-Qamar',         ayahs:55,  type:'Meccan',  juz:27 },
  { n:55,  ar:'الرحمن',        en:'Ar-Rahman',        ayahs:78,  type:'Medinan', juz:27 },
  { n:56,  ar:'الواقعة',       en:"Al-Waqi'ah",       ayahs:96,  type:'Meccan',  juz:27 },
  { n:57,  ar:'الحديد',        en:'Al-Hadid',         ayahs:29,  type:'Medinan', juz:27 },
  { n:58,  ar:'المجادلة',      en:'Al-Mujadila',      ayahs:22,  type:'Medinan', juz:28 },
  { n:59,  ar:'الحشر',         en:'Al-Hashr',         ayahs:24,  type:'Medinan', juz:28 },
  { n:60,  ar:'الممتحنة',      en:'Al-Mumtahanah',    ayahs:13,  type:'Medinan', juz:28 },
  { n:61,  ar:'الصف',          en:'As-Saf',           ayahs:14,  type:'Medinan', juz:28 },
  { n:62,  ar:'الجمعة',        en:"Al-Jumu'ah",       ayahs:11,  type:'Medinan', juz:28 },
  { n:63,  ar:'المنافقون',     en:'Al-Munafiqun',     ayahs:11,  type:'Medinan', juz:28 },
  { n:64,  ar:'التغابن',       en:'At-Taghabun',      ayahs:18,  type:'Medinan', juz:28 },
  { n:65,  ar:'الطلاق',        en:'At-Talaq',         ayahs:12,  type:'Medinan', juz:28 },
  { n:66,  ar:'التحريم',       en:'At-Tahrim',        ayahs:12,  type:'Medinan', juz:28 },
  { n:67,  ar:'الملك',         en:'Al-Mulk',          ayahs:30,  type:'Meccan',  juz:29 },
  { n:68,  ar:'القلم',         en:'Al-Qalam',         ayahs:52,  type:'Meccan',  juz:29 },
  { n:69,  ar:'الحاقة',        en:'Al-Haqqah',        ayahs:52,  type:'Meccan',  juz:29 },
  { n:70,  ar:'المعارج',       en:"Al-Ma'arij",       ayahs:44,  type:'Meccan',  juz:29 },
  { n:71,  ar:'نوح',           en:'Nuh',              ayahs:28,  type:'Meccan',  juz:29 },
  { n:72,  ar:'الجن',          en:'Al-Jinn',          ayahs:28,  type:'Meccan',  juz:29 },
  { n:73,  ar:'المزمل',        en:'Al-Muzzammil',     ayahs:20,  type:'Meccan',  juz:29 },
  { n:74,  ar:'المدثر',        en:'Al-Muddaththir',   ayahs:56,  type:'Meccan',  juz:29 },
  { n:75,  ar:'القيامة',       en:'Al-Qiyamah',       ayahs:40,  type:'Meccan',  juz:29 },
  { n:76,  ar:'الإنسان',       en:'Al-Insan',         ayahs:31,  type:'Medinan', juz:29 },
  { n:77,  ar:'المرسلات',      en:'Al-Mursalat',      ayahs:50,  type:'Meccan',  juz:29 },
  { n:78,  ar:'النبأ',         en:"An-Naba'",         ayahs:40,  type:'Meccan',  juz:30 },
  { n:79,  ar:'النازعات',      en:"An-Nazi'at",       ayahs:46,  type:'Meccan',  juz:30 },
  { n:80,  ar:'عبس',           en:"'Abasa",           ayahs:42,  type:'Meccan',  juz:30 },
  { n:81,  ar:'التكوير',       en:'At-Takwir',        ayahs:29,  type:'Meccan',  juz:30 },
  { n:82,  ar:'الانفطار',      en:'Al-Infitar',       ayahs:19,  type:'Meccan',  juz:30 },
  { n:83,  ar:'المطففين',      en:'Al-Mutaffifin',    ayahs:36,  type:'Meccan',  juz:30 },
  { n:84,  ar:'الانشقاق',      en:'Al-Inshiqaq',      ayahs:25,  type:'Meccan',  juz:30 },
  { n:85,  ar:'البروج',        en:'Al-Buruj',         ayahs:22,  type:'Meccan',  juz:30 },
  { n:86,  ar:'الطارق',        en:'At-Tariq',         ayahs:17,  type:'Meccan',  juz:30 },
  { n:87,  ar:"الأعلى",        en:"Al-A'la",          ayahs:19,  type:'Meccan',  juz:30 },
  { n:88,  ar:'الغاشية',       en:'Al-Ghashiyah',     ayahs:26,  type:'Meccan',  juz:30 },
  { n:89,  ar:'الفجر',         en:'Al-Fajr',          ayahs:30,  type:'Meccan',  juz:30 },
  { n:90,  ar:'البلد',         en:'Al-Balad',         ayahs:20,  type:'Meccan',  juz:30 },
  { n:91,  ar:'الشمس',         en:'Ash-Shams',        ayahs:15,  type:'Meccan',  juz:30 },
  { n:92,  ar:'الليل',         en:'Al-Layl',          ayahs:21,  type:'Meccan',  juz:30 },
  { n:93,  ar:'الضحى',         en:'Ad-Duha',          ayahs:11,  type:'Meccan',  juz:30 },
  { n:94,  ar:'الشرح',         en:'Ash-Sharh',        ayahs:8,   type:'Meccan',  juz:30 },
  { n:95,  ar:'التين',         en:'At-Tin',           ayahs:8,   type:'Meccan',  juz:30 },
  { n:96,  ar:'العلق',         en:"Al-'Alaq",         ayahs:19,  type:'Meccan',  juz:30 },
  { n:97,  ar:'القدر',         en:'Al-Qadr',          ayahs:5,   type:'Meccan',  juz:30 },
  { n:98,  ar:'البينة',        en:'Al-Bayyinah',      ayahs:8,   type:'Medinan', juz:30 },
  { n:99,  ar:'الزلزلة',       en:'Az-Zalzalah',      ayahs:8,   type:'Medinan', juz:30 },
  { n:100, ar:'العاديات',      en:"Al-'Adiyat",       ayahs:11,  type:'Meccan',  juz:30 },
  { n:101, ar:'القارعة',       en:"Al-Qari'ah",       ayahs:11,  type:'Meccan',  juz:30 },
  { n:102, ar:'التكاثر',       en:'At-Takathur',      ayahs:8,   type:'Meccan',  juz:30 },
  { n:103, ar:'العصر',         en:"Al-'Asr",          ayahs:3,   type:'Meccan',  juz:30 },
  { n:104, ar:'الهمزة',        en:'Al-Humazah',       ayahs:9,   type:'Meccan',  juz:30 },
  { n:105, ar:'الفيل',         en:'Al-Fil',           ayahs:5,   type:'Meccan',  juz:30 },
  { n:106, ar:'قريش',          en:'Quraysh',          ayahs:4,   type:'Meccan',  juz:30 },
  { n:107, ar:"الماعون",       en:"Al-Ma'un",         ayahs:7,   type:'Meccan',  juz:30 },
  { n:108, ar:'الكوثر',        en:'Al-Kawthar',       ayahs:3,   type:'Meccan',  juz:30 },
  { n:109, ar:'الكافرون',      en:'Al-Kafirun',       ayahs:6,   type:'Meccan',  juz:30 },
  { n:110, ar:'النصر',         en:'An-Nasr',          ayahs:3,   type:'Medinan', juz:30 },
  { n:111, ar:'المسد',         en:'Al-Masad',         ayahs:5,   type:'Meccan',  juz:30 },
  { n:112, ar:'الإخلاص',       en:'Al-Ikhlas',        ayahs:4,   type:'Meccan',  juz:30 },
  { n:113, ar:'الفلق',         en:'Al-Falaq',         ayahs:5,   type:'Meccan',  juz:30 },
  { n:114, ar:'الناس',         en:'An-Nas',           ayahs:6,   type:'Meccan',  juz:30 },
]

// ── AUDIO: Sheikh Yasser Al-Dosari ───────────────────────────────────────────
// Routes through our own Next.js proxy — avoids CORS and CDN blocks entirely.
// The server-side route tries multiple CDNs automatically.
export const audioUrl = n => `/api/quran/audio/${n}`

// ── TEXT: Proxied through our Next.js API ─────────────────────────────────────
// Fetches server-side to bypass CORS and regional API blocks.
export const textUrl = n => `/api/quran/${n}`
